name: build
on:
  push:
    branches: 
      - master
    paths:
      - 'geoip2influx.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'root/**'
jobs:
  push_to_ghcr_io:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: build&push
        run: |
              docker build . --tag ghcr.io/missuo/geoip2influx
              docker push ghcr.io/missuo/geoip2influx
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build&push
        run: |
          docker build . --tag missuo/geoip2influx
          docker push missuo/geoip2influx
